# Generated by Django 4.2.5 on 2023-09-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('products', models.ManyToManyField(to='education_system_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=15)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_system_api.lesson')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_system_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(to='education_system_api.product'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='users',
            field=models.ManyToManyField(through='education_system_api.View', to='education_system_api.user'),
        ),
    ]
